#!/usr/bin/env python 

# Read from the status file
import yaml
import sys
import state
import pprint
import configure
import build

def read_ginfile():
  stream = file("ginfile", "r")
  ginfile = yaml.load(stream)
  stream.close()
  return ginfile


def main():
#  ginstate = state.State.load()
  ginstate = None # until we control how state is serialized, dont do this
  try:
    if not ginstate:
      ginstate = state.State()
      ginfile = read_ginfile()
      config_node = configure.configure(ginstate, ginfile)
      build.build(ginstate, config_node, ginfile)
      ginstate.dump_graphviz()

    ginstate.process()

  except:
    print "Error"
    raise

#  finally:
#    if ginstate:
#      print "Saving state"
#      ginstate.save()


if __name__ == "__main__":
  main()
